### ISSUE TITLE
HTTPS url

### ISSUE THREAD

**Issue by brazorf** [DevFactoryCH/imagecache#10]
The url generated for images will be `http://` regardless.

I think a solution might be replacing the `URL::asset` calls in the facade with the `url()` helper, that should take into account current protocol, so if the user is browsing while in https the image will be resolved as https too.

What do you think?

**Comment by markcameron** [comment]
Sorry never tagged a working version, been in the dev branch of `3.0` since last feb. Tagged a `3.0.10`
