### ISSUE TITLE
Feature request: customizable image path

### ISSUE THREAD

**Issue by brazorf** [DevFactoryCH/imagecache#11]
I think that being forced to keep all assets in one single directory is very limiting.

The `Imagecache::get` method will search for files only in the configured directory and i think it would be a better practice to change its behaviour to allow for full path handling. For example:

1) I ask for `Imagecache::get('somefile.jpg')` => behaves as of now, looking in config directory

2) I ask for `Imagecache::get('path/to/somefile.jpg')` => load the file from `public/path/to/somefile.jpg`

**Comment by markcameron** [comment]
You can set the `base_dir` argument when calling a file, with a different path to the file.

`Imagecache::get('somefile.jpg', '80x80', ['base_dir' => 'path/to'])`

**Comment by brazorf** [comment]
Sorry to necro-bump this but the issue exists.
I mean, while `base_dir` allows for original image to be everywhere on the server, all the presets are statically stored in this location: `$this->imagecache_uri . $this->preset->name .'/'. $this->file_name;`

https://github.com/DevFactoryCH/imagecache/blob/master/src/Imagecache.php#L483

When the images store keeps growing to several hundreds files this can impact server performances.

**Comment by brazorf** [comment]
Check this out https://github.com/foothing/imagecache/commit/b59181d17fb8377a159153ed18c89eca4d63b627

What do you think?

**Comment by markcameron** [comment]
No worries on the Necro bump.

If you really need it I'll be glad to put it in. I'll see about taking that forked version commit in. I'll have to do that tomorrow though.

**Comment by brazorf** [comment]
Well i'm fine since i'm still using my own fork in my projects, but i think it would add value to this project, as i said several files in a single directory isn't good for the webserver.

**Comment by brazorf** [comment]
@markcameron if you do the merge keep in mind that fork also contains some https setting i've implemented in, but you didn't want to merge to the main project. Maybe you better just replicate the code, it's barely 5 lines ive changed there
