### ISSUE TITLE
buildImageCrop doesn't check for upscale constraints.

### ISSUE THREAD

**Issue by brazorf** [DevFactoryCH/imagecache#13]
Just noticed this and i was wondering why, the `$constraint->upsize()` is missing and it's not configurable in any way.

https://github.com/DevFactoryCH/imagecache/blob/master/src/Imagecache.php#L465
https://github.com/DevFactoryCH/imagecache/blob/master/src/Imagecache.php#L468
https://github.com/DevFactoryCH/imagecache/blob/master/src/Imagecache.php#L471

Is it a design choice?

**Comment by markcameron** [comment]
Never needed it for my use cases, since mine is to have images reduced to a certain size which all come from, what should be, higher resolution images.

**Comment by brazorf** [comment]
Well here's the use case. You have your site users to upload images, and those images display in a 800xH box. If the image is bigger than 800 than a scale will be performed on the width; if they do upload an image that is smaller, the upscale should be prevented.

**Comment by markcameron** [comment]
I understand the use case, I just don't need it. I don't have the time to implement it, so feel free to make a PR if you want.
