### ISSUE TITLE
Echoing nothing

### ISSUE THREAD

**Issue by goranata** [DevFactoryCH/imagecache#2]
Hi, I've just chosen this plugin for my L5 project.

However, when I place the following: {!! Imagecache::get($image, '600x450')->img !!} the line stay empty when I check it into the source code. The $image is the same as full URL of any image, taken from another source. Tested also with a local image, from mine /images/, but still the same.

I've followed all the instructions, added my custom 600x450 class at imagecache.presets.php, as changed the url pointint to images/imagecache/ at imagecache.config.php.

Granted permission access 775 for imagecache.

Could you please advice ?

**Comment by sirsquall** [comment]
the `$image` should not containt the full url but the relatif path `images/image.png`

and for the `'files_directory' => 'images/',` be sure tha you don't have a `/` at the beginning

**Comment by goranata** [comment]
Thank you for the reply. Yes it works ... a great package, but unfortunately, my images are from other source, so I will have to search for another package, or use for now, PHPTHUMB generator, that I know allows cropping from external source.

**Comment by sirsquall** [comment]
Okey great, yes this package is only for uploaded files, not for external files.
