### ISSUE TITLE
Str facade

### ISSUE THREAD

**Issue by fChristenson** [DevFactoryCH/imagecache#4]
Hey super nice lib and simple to use.
I installed it and noticed that the path to the "Str" facade in Imagecache.php uses the "Str" alias but in my version of Laravel 5.0 that alias is not defined out of the box.

The issue is easily fixed by altering the path in Imagechache.php or just adding the alias.

**Comment by markcameron** [comment]
Hi, yeah forgot it's not loaded out of the box / or removed completely.

I've pushed a fix to the dev branch:

`"devfactory/imagecache": "3.0.*@dev"`

mind giving it a shot and telling me if that fixes it for you? I don't have an install handy with me at the moment to test it with. If it works for you I'll tag a new version.

Thanks

**Comment by fChristenson** [comment]
Seems to work fine

**Comment by markcameron** [comment]
Perfect, tagged a new 3.0.x version!

Thanks for the feedback!
