### ISSUE TITLE
Lowercase namespace + doc issues

### ISSUE THREAD

**Issue by brazorf** [DevFactoryCH/imagecache#5]
There's an issue with the facade namespace and/or the documentation, which states to add this alias

'Imagecache'      => 'Devfactory\Imagecache\Facades\ImagecacheFacade'

while the actual facades filepath is lower case. You should either update the docs with

'Imagecache'      => 'Devfactory\Imagecache\facades\ImagecacheFacade',

or (recommended) refactor your namespaces.

*Edit*
There's another info that i think is misleading in the docs, since the ::get() method accepts as the first argument the plain filename, and then the configured path is automatically prepended.

I mean that Imagecache::get('somefile.jpg', 'preset') will work fine, while
Imagecache::get('path/to/somefile.jpg', 'preset') won't.

**Comment by markcameron** [comment]
Thanks for that, fixed the case on the folder.

Re-reading the README, if was definitely in need of an update. Mentioned some of the other functionality that was built in like `get_original()` and `delete()` as well as the optional `$args` parameter for `get()`.
