### ISSUE TITLE
scale image

### ISSUE THREAD

**Issue by sectorf8** [DevFactoryCH/imagecache#9]
What about scale an image without resize canvas?
For example... in Line 451 in ImageCache.php do resizeCanvas only if background is set in preset

 if(isset($this->preset->background_color))
        $image->resizeCanvas($this->preset->width, $this->preset->height, 'center', FALSE, $this->preset->background_color);

**Comment by markcameron** [comment]
Don't see a use case, but if someone wants to make a PR I'll look at it

**Comment by sectorf8** [comment]
Fixed in 3.0.11
